### ISSUE TITLE
Translation Assign Claims - Documentations

### ISSUE THREAD

**Issue by awxiaoxian2020** [ts-zh-docs/TypeScript-zh-Website#58]
- [x] [Nightly Builds.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/Nightly%20Builds.md)

  ## Declaration Files

  - [x] [By Example.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/By%20Example.md)
  - [x] [Consumption.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Consumption.md) #99
  - [x] [Deep Dive.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Deep%20Dive.md) #94 
  - [ ] [Do's and Don'ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Do's%20and%20Don'ts.md) #95 
  - [x] [Introduction.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Introduction.md)
  - [x] [Library Structures.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Library%20Structures.md) #98 
  - [x] [Publishing.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Publishing.md) in #97 
  - [x] [Templates.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/Templates.md) in #96 
  - [ ] [global-modifying-module.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/global-modifying-module.d.ts.md)  in #104 
  - [ ] [global-plugin.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/global-plugin.d.ts.md)
  - [ ] [global.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/global.d.ts.md)
  - [x] [module-class.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/module-class.d.ts.md) #102 
  - [ ] [module-function.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/module-function.d.ts.md) in #105
  - [ ] [module-plugin.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/module-plugin.d.ts.md)
  - [x] [module.d.ts.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/declaration-files/templates/module.d.ts.md) in #100

##   Get-Started

- [x] [TS for Functional Programmers.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/get-started/TS%20for%20Functional%20Programmers.md) in #83  
- [x] [TS for JS Programmers.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/get-started/TS%20for%20JS%20Programmers.md)
- [x] [TS for OOPers.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/get-started/TS%20for%20OOPers.md)
- [x] [TS for the New Programmer.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/get-started/TS%20for%20the%20New%20Programmer.md)

## Handbook-v2

- [x] [Basics.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Basics.md)
- [x] [Classes.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Classes.md)
- [x] [Everyday Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Everyday%20Types.md)
- [x] [Modules.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Modules.md)
- [x] [More on Functions.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/More%20on%20Functions.md)
- [x] [Narrowing.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Narrowing.md)
- [x] [Object Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Object%20Types.md)
- [x] [The Handbook.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/The%20Handbook.md)
- [x] [Type Declarations.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Declarations.md)
- [x] [Understanding Errors.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Understanding%20Errors.md)
- [x] [Conditional Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Conditional%20Types.md)
- [x] [Generics.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Generics.md)
- [x] [Indexed Access Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Indexed%20Access%20Types.md)
- [x] [Keyof Type Operator.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Keyof%20Type%20Operator.md)
- [x] [Mapped Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Mapped%20Types.md)
- [x] [Template Literal Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Template%20Literal%20Types.md)
- [x] [Typeof Type Operator.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Typeof%20Type%20Operator.md)
- [x] [Creating Types from Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Creating%20Types%20from%20Types.md)

## JavaScript

- [x] [Creating DTS files From JS.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/javascript/Creating%20DTS%20files%20From%20JS.md) in #84  
- [x] [Intro to JS with TS.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/javascript/Intro%20to%20JS%20with%20TS.md) #92 
- [x] [JSDoc Reference.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/javascript/JSDoc%20Reference.md) in #85  
- [x] [Type Checking JavaScript Files.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/javascript/Type%20Checking%20JavaScript%20Files.md) in #93 

## Module Reference

- [x] [Introduction.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/modules-reference/Introduction.md) 
- [x] [Reference.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/modules-reference/Reference.md) in #68 
- [x] [Theory.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/modules-reference/Theory.md) in #59 
- [x] [ESM-CJS-Interop.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/modules-reference/appendices/ESM-CJS-Interop.md) in #71 
- [x] #60

## Project Config

- [ ] [Compiler Options in MSBuild.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/project-config/Compiler%20Options%20in%20MSBuild.md)
- [ ] [Compiler Options.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/project-config/Compiler%20Options.md)
- [ ] [Configuring Watch.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/project-config/Configuring%20Watch.md)
- [x] [Integrating with Build Tools.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/project-config/Integrating%20with%20Build%20Tools.md) #90 
- [ ] [Project References.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/project-config/Project%20References.md)
- [x] [tsconfig.json.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/project-config/tsconfig.json.md)

## Reference

- [ ] [Advanced Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Advanced%20Types.md)
- [ ] [Declaration Merging.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Declaration%20Merging.md)
- [ ] [Decorators.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Decorators.md)
- [x] [Enums.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Enums.md) WIP in #88 
- [ ] [Iterators and Generators.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Iterators%20and%20Generators.md)
- [x] [JSX.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/JSX.md) WIP in #82 
- [x] [Mixins.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Mixins.md) in #87
- [ ] [Namespaces and Modules.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Namespaces%20and%20Modules.md)
- [ ] [Namespaces.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Namespaces.md)
- [x] [Symbols.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Symbols.md) in #91  
- [x] [Triple-Slash Directives.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Triple-Slash%20Directives.md) in #89  
- [ ] [Type Compatibility.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Type%20Compatibility.md)
- [ ] [Type Inference.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Type%20Inference.md)
- [ ] [Utility Types.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Utility%20Types.md)
- [x] [Variable Declarations.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/reference/Variable%20Declarations.md) in #86 

## Release Notes

- [x] [TypeScript 1.1.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.1.md)
- [x] [TypeScript 1.3.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.3.md)
- [x] [TypeScript 1.4.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.4.md)
- [x] [TypeScript 1.5.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.5.md)
- [x] [TypeScript 1.6.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.6.md)
- [x] [TypeScript 1.7.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.7.md)
- [x] [TypeScript 1.8.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%201.8.md)
- [x] [TypeScript 2.0.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.0.md)
- [x] [TypeScript 2.1.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.1.md)
- [x] [TypeScript 2.2.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.2.md)
- [x] [TypeScript 2.3.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.3.md)
- [x] [TypeScript 2.4.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.4.md)
- [x] [TypeScript 2.5.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.5.md)
- [x] [TypeScript 2.6.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.6.md)
- [x] [TypeScript 2.7.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.7.md)
- [x] [TypeScript 2.8.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.8.md)
- [x] [TypeScript 2.9.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%202.9.md)
- [x] [TypeScript 3.0.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.0.md)
- [x] [TypeScript 3.1.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.1.md)
- [x] [TypeScript 3.2.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.2.md)
- [x] [TypeScript 3.3.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.3.md)
- [x] [TypeScript 3.4.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.4.md)
- [x] [TypeScript 3.5.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.5.md)
- [x] [TypeScript 3.6.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.6.md)
- [x] [TypeScript 3.7.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.7.md)
- [x] [TypeScript 3.8.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.8.md)
- [x] [TypeScript 3.9.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%203.9.md)
- [x] [TypeScript 4.0.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.0.md)
- [x] [TypeScript 4.1.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.1.md)
- [x] [TypeScript 4.2.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.2.md)
- [x] [TypeScript 4.3.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.3.md)
- [x] [TypeScript 4.4.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.4.md)
- [x] [TypeScript 4.5.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.5.md)
- [x] [TypeScript 4.6.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.6.md)
- [x] [TypeScript 4.7.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.7.md)
- [x] [TypeScript 4.8.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.8.md)
- [x] [TypeScript 4.9.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%204.9.md)
- [x] [TypeScript 5.0.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%205.0.md)
- [x] [TypeScript 5.1.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/release-notes/TypeScript%205.1.md)

## Tutorials

- [x] [Angular.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/Angular.md) in #75 
- [x] [ASP.NET Core.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/ASP.NET%20Core.md) in #80 
- [x] [Babel with TypeScript.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/Babel%20with%20TypeScript.md) in #78 
- [x] [DOM Manipulation.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/DOM%20Manipulation.md) in #77 
- [x] [Gulp.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/Gulp.md)  in #76
- [x] [Migrating from JavaScript.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/Migrating%20from%20JavaScript.md) in #74 
- [x] [React.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/React.md) in #72 
- [x] [TypeScript Tooling in 5 minutes.md](https://github.com/ts-zh-docs/TypeScript-zh-Website/tree/main/docs/documentation/zh/tutorials/TypeScript%20Tooling%20in%205%20minutes.md) in #73
